### ISSUE TITLE
Minimize usage of third-party sites?

### ISSUE THREAD

**Issue by dax-dev** [OrangeFlash81/proton-city#10]
Connecting to proton.city immediately connects to fonts.googleapis.com and, more recently, google-analytics.com

I understand the usage of the Google Fonts API, though the site looks fine without it.

However, I don't understand why Google Analytics is necessary.

Some users don't want our connections hitting Google servers; if possible, can reliance on third-party resources be removed when uneccesary?

**Comment by AaronC81** [comment]
Fair enough; I understand the concern here.

I think continuing to use Google Fonts is probably best, since the font I'm using (Lato) is pretty popular so many people probably have it cached from Google's CDN.

I'd like *some sort* of analytics solution, so that I can get a rough idea of my site's popularity. I understand why people wouldn't want Google Analytics though, so I'll look into server-side options instead.

Thanks for your feedback.
